CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    email         VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20) NOT NULL DEFAULT 'USER'
);

CREATE TABLE rooms (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE tickets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room        BIGINT NOT NULL REFERENCES rooms(id),
    status      VARCHAR(20) NOT NULL DEFAULT 'WAITING',
    user_id     BIGINT NOT NULL REFERENCES users(id),
    operator_id BIGINT REFERENCES users(id),
    taken_at    TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT now(),
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id       BIGINT NOT NULL REFERENCES tickets(id),
    user_id         BIGINT NOT NULL REFERENCES users(id),
    content         TEXT NOT NULL,
    sent_at         TIMESTAMP NOT NULL DEFAULT now()
);

